<?php

declare (strict_types=1);
namespace Syde\Vendor;

// phpcs:disable Inpsyde.CodeQuality.LineLength.TooLong
use Syde\Vendor\Dhii\Services\Factory;
return new Factory(['webhooks.settings.fields', 'worldline_payment_gateway.api.default_test_endpoint', 'worldline_payment_gateway.api.default_live_endpoint'], static function (array $webhookFields, string $defaultTestEndpoint, string $defaultLiveEndpoint): array {
    $apiFields = ['pspid' => ['title' => \__('PSPID', 'worldline-for-woocommerce'), 'type' => 'text', 'description' => \__('Enter your Merchant ID or your Worldline Login Name.', 'worldline-for-woocommerce'), 'desc_tip' => \true], 'live_mode' => ['title' => \__('Live mode', 'worldline-for-woocommerce'), 'type' => 'checkbox', 'label' => \__('Use the live environment', 'worldline-for-woocommerce'), 'default' => 'no'], 'test_api_key' => ['title' => \__('Test API Key', 'worldline-for-woocommerce'), 'type' => 'text', 'description' => \__('Find/create the API Key in Developer tab > Payment API on your Worldline Merchant Portal Dashboard(Test).', 'worldline-for-woocommerce'), 'desc_tip' => \true, 'custom_attributes' => ['autocomplete' => 'off']], 'test_api_secret' => ['title' => \__('Test API Secret', 'worldline-for-woocommerce'), 'type' => 'password', 'description' => \__('Find/create the API Secret in Developer tab > Payment API on your Worldline Merchant Portal Dashboard(Test).', 'worldline-for-woocommerce'), 'desc_tip' => \true, 'custom_attributes' => ['autocomplete' => 'off']], 'test_api_endpoint' => ['title' => \__('Test API Endpoint', 'worldline-for-woocommerce'), 'type' => 'text', 'default' => $defaultTestEndpoint, 'description' => \__('Enter Endpoint URL congifured on your test account.', 'worldline-for-woocommerce'), 'desc_tip' => \true], 'live_api_key' => ['title' => \__('Live API Key', 'worldline-for-woocommerce'), 'type' => 'text', 'description' => \__('Find/create the API Key in Developer tab > Payment API on your Worldline Merchant Portal Dashboard.', 'worldline-for-woocommerce'), 'desc_tip' => \true, 'custom_attributes' => ['autocomplete' => 'off']], 'live_api_secret' => ['title' => \__('Live API Secret', 'worldline-for-woocommerce'), 'type' => 'password', 'description' => \__('Find/create the API Secret in Developer tab > Payment API on your Worldline Merchant Portal Dashboard.', 'worldline-for-woocommerce'), 'desc_tip' => \true, 'custom_attributes' => ['autocomplete' => 'off']], 'live_api_endpoint' => ['title' => \__('Live API Endpoint', 'worldline-for-woocommerce'), 'type' => 'text', 'default' => $defaultLiveEndpoint, 'description' => \__('Enter Endpoint URL congifured on your live account.', 'worldline-for-woocommerce'), 'desc_tip' => \true]];
    $otherFields = ['debug_logging' => ['title' => \__('Advanced logging', 'worldline-for-woocommerce'), 'type' => 'checkbox', 'label' => \__('Enable debug logging', 'worldline-for-woocommerce'), 'default' => 'no', 'desc_tip' => \true, 'description' => \__('Write more details into the logs, such as HTTP requests.', 'worldline-for-woocommerce')]];
    $checkoutFields = ['checkout_behavior_title' => ['title' => \__('Checkout appearance', 'worldline-for-woocommerce'), 'type' => 'title'], 'payment_button_title' => ['title' => \__('Payment button title', 'worldline-for-woocommerce'), 'type' => 'text', 'description' => \__('Personalize the Checkout Button text.', 'worldline-for-woocommerce'), 'desc_tip' => \true], 'checkout_type' => ['title' => \__('Checkout type', 'worldline-for-woocommerce'), 'type' => 'select', 'default' => 'hosted', 'options' => ['hosted' => \__('Full redirection to Worldline Payment Page', 'worldline-for-woocommerce')]], 'card_brands_display' => ['title' => \__('Grouped Cards', 'worldline-for-woocommerce'), 'label' => \__('Enable card grouping', 'worldline-for-woocommerce'), 'type' => 'checkbox', 'default' => 'no'], 'stored_card_buttons' => ['title' => \__('Show tokenized cards', 'worldline-for-woocommerce'), 'type' => 'checkbox', 'label' => \__('Enable', 'worldline-for-woocommerce'), 'description' => \__('When a customer has stored cards, additional "Pay with your stored card ..." buttons will be displayed in checkout.', 'worldline-for-woocommerce'), 'desc_tip' => \true, 'default' => 'yes']];
    $surchargeFields = ['surcharge_title' => ['title' => \__('Surcharge settings', 'worldline-for-woocommerce'), 'type' => 'title'], 'surcharge_enable' => ['title' => \__('Surcharge', 'worldline-for-woocommerce'), 'type' => 'checkbox', 'label' => \__('Enable', 'worldline-for-woocommerce'), 'description' => \__('Instruct the payment platform to calculate and apply a surcharge amount to a transaction, based on the merchant’s surcharge configuration, net amount, and payment product type.', 'worldline-for-woocommerce') . '<br>' . \__('Please make sure that Surcharging is active on your Worldline account. If it is not configured properly, the payments will not be processed.', 'worldline-for-woocommerce')]];
    $advancedFields = ['advanced_title' => ['title' => \__('Advanced settings', 'worldline-for-woocommerce'), 'type' => 'title'], 'authorization_mode' => ['title' => \__('Authorization mode', 'worldline-for-woocommerce'), 'type' => 'select', 'default' => 'authorization', 'options' => ['authorization' => \__('Authorization', 'worldline-for-woocommerce'), 'sale' => \__('Sale', 'worldline-for-woocommerce')], 'description' => \__('Define whether you want to work in one step (money captured directly; SALE) or in two steps (authorization followed by a capture; Authorization).', 'worldline-for-woocommerce'), 'desc_tip' => \true], 'credit_card_authorization_mode' => ['title' => \__('Authorization mode for credit cards', 'worldline-for-woocommerce'), 'type' => 'select', 'default' => 'final_authorization', 'options' => ['final_authorization' => \__('Final authorization', 'worldline-for-woocommerce'), 'pre_authorization' => \__('Pre-authorization', 'worldline-for-woocommerce')], 'description' => \__("Use authorization to block the funds of your customers for a period of 7 days. Those can't be reversed and need to be captured for the full amount. Use a preauthorization to block the funds of your customers for a period of 30 days. The amount captured can be lower than the authorized amount. Note that all acquirers and activity sectors do not support preauthorizations.", 'worldline-for-woocommerce'), 'desc_tip' => \true], 'enforce_3dsv2' => ['title' => \__('Strong customer authentication', 'worldline-for-woocommerce'), 'type' => 'checkbox', 'label' => \__('Enforce 3DSv2', 'worldline-for-woocommerce'), 'default' => 'no']];
    return \array_merge(['enabled' => ['title' => \__('Enable/Disable', 'worldline-for-woocommerce'), 'type' => 'checkbox', 'label' => \__('Enable Worldline Payments', 'worldline-for-woocommerce'), 'default' => 'no']], $apiFields, $webhookFields, $otherFields, $checkoutFields, $surchargeFields, $advancedFields);
});
